import { z } from "zod"

export const createInvoiceSchema = z.object({
  customerId: z.string().optional(),
  paymentTerms: z.string().default("Due Upon Receipt"),
  invoiceDate: z.string().or(z.date()),
  dueDate: z.string().or(z.date()).optional(),
  memo: z.string().optional(),
  deliveryDate: z.string().or(z.date()).optional(),
  project: z.string().optional(),
  saleCirculation: z.string().optional(),
  salePerson: z.string().optional(),
  stationLocation: z.string().optional(),
  partialPayment: z.number().min(0).optional(),
  paymentMethod: z.string().default("cash"),
  paymentNote: z.string().optional(),
  discountAmount: z.number().min(0).optional(),
  discountPercent: z.number().min(0).max(100).optional(),
  attachments: z.array(z.object({
    title: z.string(),
    filename: z.string(),
  })).optional(),
  items: z.array(z.object({
    variantId: z.string().optional(),
    description: z.string().optional(),
    quantity: z.number().positive().default(1),
    rate: z.number().min(0).default(0),
    taxRate: z.number().min(0).max(100).default(0),
    taxType: z.enum(["INCL", "EXCL"]).default("EXCL"),
    rateType: z.enum(["whole", "retail"]).default("retail"),
  })).min(1),
  branchId: z.string().optional(),
})

export const updateInvoiceSchema = z.object({
  customerId: z.string().optional(),
  paymentTerms: z.string().optional(),
  invoiceDate: z.string().or(z.date()).optional(),
  dueDate: z.string().or(z.date()).optional(),
  memo: z.string().optional(),
  deliveryDate: z.string().or(z.date()).optional(),
  project: z.string().optional(),
  saleCirculation: z.string().optional(),
  salePerson: z.string().optional(),
  stationLocation: z.string().optional(),
  partialPayment: z.number().min(0).optional(),
  paymentMethod: z.string().optional(),
  paymentNote: z.string().optional(),
  discountAmount: z.number().min(0).optional(),
  discountPercent: z.number().min(0).max(100).optional(),
  status: z.string().optional(),
  attachments: z.array(z.object({
    title: z.string(),
    filename: z.string(),
  })).optional(),
  items: z.array(z.object({
    variantId: z.string().optional(),
    description: z.string().optional(),
    quantity: z.number().positive().default(1),
    rate: z.number().min(0).default(0),
    taxRate: z.number().min(0).max(100).default(0),
    taxType: z.enum(["INCL", "EXCL"]).default("EXCL"),
    rateType: z.enum(["whole", "retail"]).default("retail"),
  })).optional(),
})
